# Generated by Django 3.0.5 on 2021-05-03 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import incomes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('spentOn', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Incomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', djongo.models.fields.ArrayField(model_container=incomes.models.Income)),
                ('users', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
